FROM python:3.12-slim 

# Set up environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install and set up node.js
RUN apt-get update && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean

# Create and set the working directory
WORKDIR /src

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY . .

# Expose the port for application (5000 is default flask port)
EXPOSE 5000 

# Specify the command to run on container start
CMD ["flask", "--app=app.py", "run", "--host=0.0.0.0"]

