FROM python:3.12-slim 

# Set up environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create and set the working directory
WORKDIR /app

COPY requirements.txt /app
COPY app.py /app

RUN pip3 install -r requirements.txt

# Expose the port yfor application
EXPOSE 81

ENTRYPOINT ["python3"]
CMD ["app.py"]

# Specify the command to run on container start
#CMD ["ls"]
#CMD ["python", "app.py", "run"]
#CMD ["flask", "--app /CPUStatpage/app.py", "run"]
