FROM golang:1.24-alpine AS builder

WORKDIR /PiDashboard/src

COPY go.mod go.sum ./ 

RUN go mod download

# COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o server .

FROM alpine:3.21 AS final 

WORKDIR /PiDashboard

# copy all files from builder stage to final stage. Will copy the whole /src instead of 
#the /src/server only since we need the .go files 

#Try not copying .go files
COPY --from=builder /PiDashboard . 

COPY static ./static

COPY certs ./certs

COPY URLs.yaml .

EXPOSE 8080

# Specify the command to run on container start
CMD ["./src/server"]
