FROM golang:1.24-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o "./src/server" .
# RUN go build -o server

FROM alpine:3.21 AS final 

WORKDIR /src

COPY --from=builder /src/server .

EXPOSE 8080

# Specify the command to run on container start
CMD ["/src/server"]
