services:
  bme280-app:
      build:
        context: app
        dockerfile: dockerfile

      container_name: bme280-app

      ports:
        - 8082:5000  # Map host's port 8082 to container port 5000(default flask port)

      volumes:
        - /home/Tth/Databases/bme280-app.db:/database/bme280-app.db

      devices:
        - /dev/i2c-1

      cap_add:
        - NET_ADMIN

      restart: unless-stopped