networks:
  dns_net: 
    external: true
  traefik:
    external: true    

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - traefik
      - dns_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.pihole.rule=Host(`pihole.rpi.home.arpa`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp

    environment:
      TZ: 'Singapore'
      FTLCONF_webserver_api_password: 'pihole'
      FTLCONF_dns_upstreams: 'unbound#53'
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_dns_cache_size: 0 #remove me for prod
    volumes:
      - '/opt/homelab/PiHole/etc-pihole:/etc/pihole'
      - '/opt/homelab/PiHole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: pedantic/unbound:latest
    volumes:
      - '/opt/homelab/Unbound:/opt/unbound/etc/unbound'
    networks:
      dns_net:
        ipv4_address: 172.18.0.2 #For Pihole and dnsmasq configs
    restart: unless-stopped