services:
  cpu-stats:
      build:
        context: app
        dockerfile: ./dockerfiles/flask-dockerfile

      container_name: cpu-stats-app

      ports:
        - 8081:5000  # Map host's port 8081 to container port 5000(default flask port)

      volumes:
        - ./db_data:/home/Tth/Databases/cpu-stats-app.db
        - .:/app:ro
        - /usr:/usr 

      environment:
        - LD_LIBRARY_PATH=/usr/lib

      devices:
        - /dev/vchiq
        - /dev/vcio

      cap_add:
        - NET_ADMIN

      restart: unless-stopped