redis:
  build: docker-redis-rpi
  volumes:
    - ./redis.conf:/etc/redis.conf

check_temperature:
  build: docker-python3-rpi
  container_name: cpu-stats-app
  devices:
    - "/dev/vchiq"
  environment:
    - LD_LIBRARY_PATH=/usr/lib
  volumes:
    - /usr:/usr 
    - ./temperature_update.py:/etc/temperature_update.py:ro
  links:
    - redis 
  command: python3 /etc/temperature_update.py

cpu-stats:
    build:
      context: app
      dockerfile: dockerfile
    volumes:
      - .:/app:ro
      - /usr:/usr 

    environment:
      - LD_LIBRARY_PATH=/usr/lib

    devices:
      - /dev/vchiq
      - /dev/vcio

    cap_add:
      - NET_ADMIN

    restart: unless-stopped