services:
  cpu-stats:
    build:
      context: app
      dockerfile: dockerfile

    container_name: cpu-stats-app

    ports:
      - "8081:5000"  # Map host's port 8081 to container port 5000(default flask port)

    volumes:
      - .:/app:ro

    cap_add:
      - NET_ADMIN
      
    restart: unless-stopped