redis:
  build: docker-redis-rpi
  volumes:
    - ./redis.conf:/etc/redis.conf

cpu-stats:
    build:
      context: app
      dockerfile: dockerfile
    volumes:
      - .:/app:ro
      - /usr:/usr 

    environment:
      - LD_LIBRARY_PATH=/usr/lib

    devices:
      - /dev/vchiq
      - /dev/vcio

    cap_add:
      - NET_ADMIN

    restart: unless-stopped