version: '3'
services:
  cpu-stats:
    build:
      context: .
      dockerfile: dockerfile
    #image: python:3.12-slim  # You can replace this with your own image if needed
    container_name: cpu-stats-app
    ports:
      - "8081:81"  # Expose port for your web app
    volumes:
      - .:/app:ro
    cap_add:
      - NET_ADMIN
    restart: unless-stopped