FROM python:3.12-slim 

# Set up environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install flask and python
RUN apt update
RUN apt install python3-pip -y
RUN pip3 install Flask

# Create and set the working directory
WORKDIR /app

# Copy all code in this folder to current directory (/app)
COPY . .

# Expose the port yfor application
EXPOSE 81

# Specify the command to run on container start
CMD ["python3", "-m", "flask", "--app=/CPUStatpage/app.py", "run"]
#CMD ["flask", "run"]