redis:
    build: 
      dockerfile: /dockerfiles/redis-dockerfile
    volumes:
      - ./redis.conf:/etc/redis.conf

cpu-stats:
    build:
      context: app
      dockerfile: /dockerfiles/flask-dockerfile
    volumes:
      - .:/app:ro
      - /usr:/usr 

    environment:
      - LD_LIBRARY_PATH=/usr/lib

    devices:
      - /dev/vchiq
      - /dev/vcio

    cap_add:
      - NET_ADMIN

    restart: unless-stopped